# this file is only used during local development, see master branch for what is used in production

[book]
authors = ["Jolie Team"]
language = "en"
multilingual = false
src = "src"
title = "Jolie Documentation"

[build]
create-missing = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["src/assets/js/mermaid.min.js", "src/assets/js/mermaid-init.js"]
edit-url-template = "https://github.com/jolie/docs/edit/v1.12.x/{path}"

[output.html.font]
enable = true
woff = true

# [output.html.fold]
# enable = true
